title = "Photos by Thomas"
baseURL = "https://photosbythomas.netlify.app"
theme = ["FixIt"]


defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# default amount of posts in each pages
paginate = 12
# copyright description used only for seo schema
copyright = "Thomas Evensen"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = false
# whether to use emoji code
enableEmoji = true
# googleAnalytics = "G-8D3XWF30Y6"

# Author config
[author]
  name = "Thomas Evensen - all photos are copyrighted by law"
  email = "thomeven@gmail.com"
  link = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # date format
  dateFormat = "2006-01-02"

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = ""
      # title name
      name = "Photos by Thomas"

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2024

  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    # rss = 10

  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    # rss = 10

  # Home page config
  [params.home]
   # Home page profile
    [params.home.profile]
      enable = false
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page (HTML format is supported)

    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 20
        # Page global config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = true
    # whether to enable the ruby extended syntax
    ruby = false
    # whether to enable the fraction extended syntax
    fraction = false
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show the full text content in RSS
    # rssFullText = true
    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = false
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Multilingual
[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    # copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
      [[languages.en.menu.main]]
        weight = 4
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
    [languages.en.params]
      [languages.en.params.home]
        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = "thomeven@gmail.com"
          avatarURL = "/images/me.png"
          title = "Some photos by Thomas"
          typeit = false
          social = false
          disclaimer = ""
